### ISSUE TITLE
Question - more usage example

### ISSUE THREAD

**Issue by thim81** [MauroJr/mongo-observer#1]
Hi Mauro,

I'm interested in using your mongo-observer since it uses the oplog method.

Do you have more examples how to use it to watch for updates / inserts in certain collections?

Regards,
Tim

**Comment by MauroJr** [comment]
Hi Tim,

I'm working to release until tomorrow a version with new features, including documentation and more examples.

I hope this project will be useful.

Best regards,
Mauro Junior

**Comment by thim81** [comment]
Looking forward to this.
Since I miss this behaviour default in Mongo, since it can provide for powerfull trigger / procedures.
